FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --default-timeout 120 -r requirements.txt || true

COPY . .

EXPOSE 8090

CMD ["python", "manage.py", "runserver", "0.0.0.0:8090"]
